stages:
  - test
  - lint
  - build

test:
  image: rust
  script:
    - cargo test

lint:
  image: rust
  script:
    - rustup component add clippy rustfmt
    - cargo fmt --check
    - cargo clippy -- -D warnings

build:
  image: rust
  variables:
    TZWITTER_L1_CONTRACT: "KT1..."
  script:
    - cargo build --release
