[package]
name = "counter-kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tezos_data_encoding = {version = "0.4"}
tezos-smart-rollup = "0.1.0"